### PR TITLE
Update for CUDA 12.4.1

### PR DESCRIPTION
**Pull request by adibbley**
xref: https://github.com/conda-forge/cuda-feedstock/issues/23

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by adibbley** [comment]
Requires cuda-nvdisasm to be updated first.

**Comment by adibbley** [comment]
@conda-forge-admin, please restart ci

**Comment by jakirkham** [comment]
One of the Travis CI jobs on `main` timed out. Restarted [here]( https://app.travis-ci.com/github/conda-forge/cuda-cuobjdump-feedstock/jobs/620204865 )

**Comment by jakirkham** [comment]
Remaining packages are now uploaded. Just need to finish mirroring

**Pull request merged**
